In [9]:
import pandas as pd
import os
from plotnine import *
%matplotlib inline

### First we'll load in the 'Energy and Mining' data obtained from the World Bank data 
__Many of the "countries" in the data set are actually regions, or groups of countries, and are unneccessary for this analysis, so those were removed by country code.__

In [106]:
data=pd.read_csv('energy-and-mining.csv')
not_countries=['WLD','HIC','OED','PST','IBT','LMY','MIC','NAC','IBD',
              'UMC','EUU','EAS','LTE','EMU','ECS','EAR','EAP','TEA',
              'HPC','MNA','TSS','SSF','TMN','SSA','TSA','IDB','IDX',
              'CEB','TEC','PRE','LAC','FCS','LMC','TLA','LDC','MEA',
              'LIC','IDA','ECA','PSS','OSS','CSS','LCN','ARB','SST'
              ,'SAS']
data=data[~data['Country Code'].isin(not_countries)]
data=data.rename(columns={'Country Name':'Country'})
data

,Country,Country Code,Year,Access to electricity (% of population),"Access to electricity, rural (% of rural population)","Access to electricity, urban (% of urban population)",Adjusted savings: energy depletion (% of GNI),Adjusted savings: energy depletion (current US$),Adjusted savings: mineral depletion (% of GNI),Adjusted savings: mineral depletion (current US$),...,Oil rents (% of GDP),Ores and metals exports (% of merchandise exports),Ores and metals imports (% of merchandise imports),Pump price for diesel fuel (US$ per liter),Pump price for gasoline (US$ per liter),Renewable electricity output (% of total electricity output),Renewable energy consumption (% of total final energy consumption),Time required to get electricity (days),Total natural resources rents (% of GDP),Value lost due to electrical outages (% of sales for affected firms)
0,Albania,ALB,1977,0.000000,0.000000,0.000000,0.000000,6.710147e+07,0.000000,6.867981e+06,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0
1,Azerbaijan,AZE,2013,100.000000,100.000000,100.000000,18.040857,1.271447e+10,0.063163,4.451467e+07,...,23.570725,0.487671,1.175848,0.0,0.0,6.671234,2.526095,97.0,26.484921,1.0
2,Azerbaijan,AZE,2015,100.000000,100.000000,100.000000,8.278651,4.225966e+09,0.093160,4.755507e+07,...,11.029707,0.964430,2.218885,0.0,0.0,7.039857,2.310758,77.0,13.345366,0.0
3,Burkina Faso,BFA,1993,6.100000,0.600000,29.400000,0.000000,0.000000e+00,0.000000,0.000000e+00,...,0.000000,0.000000,0.000000,0.0,0.0,21.860465,93.479993,0.0,7.687432,0.0
4,Bulgaria,BGR,1989,0.000000,0.000000,0.000000,0.098619,2.105675e+07,0.973120,2.077774e+08,...,0.082350,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,2.729569,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14694,St. Vincent and the Grenadines,VCT,1999,78.700058,72.969006,85.754982,0.000000,0.000000e+00,0.000000,0.000000e+00,...,0.000000,0.078428,0.674192,0.0,0.0,19.441341,6.544175,0.0,0.022043,0.0
14695,Vietnam,VNM,1996,81.548157,76.546597,98.697975,2.803882,6.804382e+08,0.009764,2.369481e+06,...,3.500787,0.000000,0.000000,0.0,0.0,70.868744,62.866009,0.0,6.901911,0.0
14696,Kosovo,XKX,1977,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0
14697,"Yemen, Rep.",YEM,1970,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0
14700,Tonga,TON,1997,83.281296,79.298087,96.671638,0.000000,0.000000e+00,0.000000,0.000000e+00,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,1.263760,0.0,0.049399,0.0

__Unfortunately, the previous dataset was missing **total** CO2 emission, so we need a separate dataset for that, also obtained from World Bank. This comes in the form of a pivot table, so we'll melt this into a dataframe that will be easier to use in Vega Lite.__

In [107]:
os.chdir('/Users/nickbohmann/Documents/uw/dataviz/A2_stuff/World-Bank-Data-by-Indicators/engergy-and-mining')
data_new=pd.read_csv('data_new.csv')
data_new=data_new[~data_new['Country Code'].isin(not_countries)]
data_new=data_new.drop(columns=['Indicator Code','Indicator Name','Country Code'])
data_new=pd.melt(data_new, 
            id_vars='Country Name', 
            value_vars=list(data_new.columns[1:]), # list of days of the week
            var_name='Year', 
            value_name='CO2 Emission')
data_new=data_new[~data_new.Year.str.contains('Unnamed: 65')]
data_new.to_csv('tot_co2.csv')
data_new

       Country Name  Year  CO2 Emission
0             Aruba  1960     11092.675
1       Afghanistan  1960       414.371
2            Angola  1960       550.050
3           Albania  1960      2024.184
4           Andorra  1960           NaN
...             ...   ...           ...
13293        Kosovo  2020           NaN
13294   Yemen, Rep.  2020           NaN
13295  South Africa  2020           NaN
13296        Zambia  2020           NaN
13297      Zimbabwe  2020           NaN

[13298 rows x 3 columns]